"""create cars table

Revision ID: 7dc425a8916e
Revises: 
Create Date: 2025-11-16 17:10:37.626834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc425a8916e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('build_month', sa.Integer(), nullable=True),
    sa.Column('buy_year', sa.Integer(), nullable=True),
    sa.Column('buy_month', sa.Integer(), nullable=True),
    sa.Column('purchase_cost', sa.Float(), nullable=True),
    sa.Column('road_taxes_yearly', sa.Float(), nullable=True),
    sa.Column('insurance_monthly', sa.Float(), nullable=True),
    sa.Column('fuel_per_km', sa.Float(), nullable=True),
    sa.Column('depreciation_k', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
