"""create cars table

Revision ID: 7dc425a8916e
Revises: 
Create Date: 2025-11-16 17:10:37.626834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision: str = '7dc425a8916e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=True),
        sa.Column('build_year', sa.Integer(), nullable=True),
        sa.Column('build_month', sa.Integer(), nullable=True),
        sa.Column('buy_year', sa.Integer(), nullable=True),
        sa.Column('buy_month', sa.Integer(), nullable=True),
        sa.Column('purchase_cost', sa.Float(), nullable=True),
        sa.Column('road_taxes_yearly', sa.Float(), nullable=True),
        sa.Column('insurance_monthly', sa.Float(), nullable=True),
        sa.Column('fuel_per_km', sa.Float(), nullable=True),
        sa.Column('depreciation_k', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    cars_table = table('cars',
        column('name', sa.String),
        column('type', sa.String),
        column('build_year', sa.Integer),
        column('build_month', sa.Integer),
        column('buy_year', sa.Integer),
        column('buy_month', sa.Integer),
        column('purchase_cost', sa.Float),
        column('road_taxes_yearly', sa.Float),
        column('insurance_monthly', sa.Float),
        column('fuel_per_km', sa.Float),
        column('depreciation_k', sa.Float),
    )

    op.bulk_insert(cars_table, [
            {
                'name': 'tesla_model_3',
                'type': 'buy',
                'build_year': 2019,
                'build_month': 1,
                'buy_year': 2025,
                'buy_month': 11,
                'purchase_cost': 18000.0,
                'road_taxes_yearly': 1000.0,
                'insurance_monthly': 280.0,
                'fuel_per_km': 0.08,
                'depreciation_k': 0.08
            },
            {
                'name': 'opel_corsa_e',
                'type': 'buy',
                'build_year': 2022,
                'build_month': 1,
                'buy_year': 2025,
                'buy_month': 11,
                'purchase_cost': 17000.0,
                'road_taxes_yearly': 700.0,
                'insurance_monthly': 180.0,
                'fuel_per_km': 0.08,
                'depreciation_k': 0.08
            }
        ])

def downgrade():
    op.drop_table('cars')
